ALTER TABLE scan_results ADD COLUMN IF NOT EXISTS profile VARCHAR(20) DEFAULT 'all';
ALTER TABLE scan_results ADD COLUMN IF NOT EXISTS high INT NOT NULL DEFAULT 0;
ALTER TABLE scan_results ADD COLUMN IF NOT EXISTS medium INT NOT NULL DEFAULT 0;
ALTER TABLE scan_results ADD COLUMN IF NOT EXISTS low INT NOT NULL DEFAULT 0;
ALTER TABLE scan_results ADD COLUMN IF NOT EXISTS info INT NOT NULL DEFAULT 0;
