ALTER TABLE servers ADD COLUMN IF NOT EXISTS ssh_user VARCHAR(255) NOT NULL DEFAULT 'root';
ALTER TABLE servers ADD COLUMN IF NOT EXISTS ssh_auth_type VARCHAR(50) NOT NULL DEFAULT 'key';
ALTER TABLE servers ADD COLUMN IF NOT EXISTS ssh_key TEXT DEFAULT '';
ALTER TABLE servers ADD COLUMN IF NOT EXISTS ssh_password TEXT DEFAULT '';
ALTER TABLE servers ADD COLUMN IF NOT EXISTS container_count INTEGER NOT NULL DEFAULT 0;
