ALTER TABLE servers ADD COLUMN IF NOT EXISTS connection_type VARCHAR(20) NOT NULL DEFAULT 'ssh';
ALTER TABLE servers ADD COLUMN IF NOT EXISTS is_self BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE servers ADD COLUMN IF NOT EXISTS self_hostname VARCHAR(255) DEFAULT '';
