CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS users (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email       VARCHAR(255) NOT NULL UNIQUE,
    name        VARCHAR(255) NOT NULL,
    password_hash TEXT NOT NULL,
    totp_secret TEXT DEFAULT '',
    totp_enabled BOOLEAN DEFAULT FALSE,
    role        VARCHAR(50) NOT NULL DEFAULT 'developer',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- Seed default admin user (password: admin123)
-- bcrypt hash generated by Go's x/crypto/bcrypt
INSERT INTO users (id, email, name, password_hash, role)
VALUES (
    gen_random_uuid(),
    'admin@anjungan.id',
    'Admin',
    '$2a$10$y1zEEdIRbUDKubaycmHgyuFNmkNmuAUD735xb/EzVlNwuC.F25ipa',
    'admin'
) ON CONFLICT (email) DO NOTHING;
